const gendersJson = [
  { name: "cat", value: 1 },
  { name: "cats", value: 2 },
  { name: "funny cat", value: 3 },
  { name: "dog", value: 4 },
  { name: "dogs", value: 5 },
  { name: "funny dog", value: 6 },
  { name: "funny dogs", value: 7 },
  { name: "animals", value: 8 },
  { name: "baby", value: 9 },
  { name: "babies", value: 10 },
  { name: "puppies", value: 11 },
  { name: "kid", value: 12 },
  { name: "kids", value: 13 },
  { name: "kids and animals", value: 14 },
  { name: "trolling", value: 15 },
  { name: "birds", value: 16 },
  { name: "birds talk like human", value: 17 },
  { name: "horse", value: 18 },
  { name: "horses", value: 19 },
  { name: "funny horse", value: 20 },
  { name: "horses are much more funny than cats", value: 21 },
  { name: "cute and funny horse", value: 22 },
  { name: "funnies horse", value: 23 },
]

export default gendersJson